import type { Metadata } from "next";
import "./globals.css";

import localFont from "next/font/local";
import { Playfair_Display,Montserrat, Mrs_Saint_Delafield, Imperial_Script } from "next/font/google";


const bohemeFloral = localFont({
  src: [
    {
      path: "../public/fonts/BohemeFloral.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-boheme",
});
const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"], // choose weights you need
  variable: "--font-playfair",
});
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-montserrat",
});
const mrsSaintDelafield = Mrs_Saint_Delafield({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-mrs-saint-delafield",
});
const imperialScript = Imperial_Script({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-imperial-script",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bohemeFloral.variable} ${playfair.variable} ${montserrat.variable} ${mrsSaintDelafield.variable} ${imperialScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
